
import type { Metadata } from "next";
import { Inter, Sora, Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/main/Footer";
import Loading from "./Loading";
import { Head } from "next/document";

const inter = Nunito({ subsets: ["latin"] }); 

export const metadata: Metadata = {
	title: "Home || Q-Labs Global",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="image" href="favicon.ico" sizes="32x32" />
			</head>
			{/* <Suspense fallback={<Loading/>}> */}
			<body className={`${inter.className} w-full bg-secondary `}>
				<div className=" flex flex-col ">
					<Loading/>
					<div className=" px-4 lg:px-[200px]   z-[60]">
						<Header />
					</div>
					<div className=" flex-1 ">{children}</div>
					<div className=" lg:px-[200px] bg-accent/70">
						<Footer />
					</div>
				</div>
			</body>
			{/* </Suspense> */}
		</html>
	);
}
