import type { Metadata } from "next";
import { Inter, Sora, Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/main/Footer";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Q-Labs Global",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} w-full bg-secondary `}>
				<div className=" flex flex-col ">
					<div className=" px-4 lg:px-[200px]   z-[60]">
						<Header />
					</div>
					<div className=" flex-1 ">{children}</div>
					<div className=" lg:px-[200px] bg-accent/70">
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
